dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  path: ^1.9.0
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  camera: ^0.11.0+2
  pdf: ^3.11.1
  printing: ^5.13.1        # Isay 5.13.1 kar dein (Downgrade)
  share_plus: ^10.1.0      # Isay ^10.1.0 ya latest kar dein
  image_picker: ^1.1.2
  cupertino_icons: ^1.0.8